//! Save-file safety: three kids share one localStorage value, so one bad slot
//! (or a schema change) must never cost the other two their adventures, and a
//! slot this build can't read must survive untouched until one that can.
//!
//! Everything here runs the production codec through `InMemoryBackend`, which
//! goes through the same decode → migrate → encode → back-up path as
//! `LocalStorageBackend`.

mod common;

use common::Harness;
use robot_buddy_domain::economy::wardrobe;
use robot_buddy_domain::learning::learner_profile::LearnerProfile;
use robot_buddy_game::game::GameState;
use robot_buddy_game::input::FrameInput;
use robot_buddy_game::save::{
    backup_key, decode_saves, InMemoryBackend, SaveBackend, SaveData, StoredSlot, STORAGE_KEY,
};
use robot_buddy_game::ui::title_screen::{self, TitleActionKind};
use serde::{Deserialize, Serialize};
use serde_json::value::RawValue;

/// Exactly what `main` writes to localStorage today: two kids (Ari in slot 1,
/// a veteran diver with cosmetics and a dolphin buddy; Noa in slot 3), slot 2
/// free. Generated by serializing `main`'s own `SaveData` — don't hand-edit.
const MAIN_SAVES: &str = include_str!("fixtures/main_saves.json");

/// The raw JSON text of each slot, as stored.
fn raw_slots(json: &str) -> Vec<String> {
    let entries: Vec<&RawValue> = serde_json::from_str(json).expect("a slot array");
    entries.iter().map(|r| r.get().to_string()).collect()
}

fn stored(backend: &InMemoryBackend) -> String {
    backend.raw(STORAGE_KEY).expect("saves are stored")
}

/// Noa's save with one field a build can't read: dum_dums as a word.
fn corrupt_noa() -> String {
    let noa = raw_slots(MAIN_SAVES)[2].clone();
    assert!(noa.contains("\"dum_dums\":3,"), "fixture shape changed");
    noa.replace("\"dum_dums\":3,", "\"dum_dums\":\"lots\",")
}

fn ari() -> String {
    raw_slots(MAIN_SAVES)[0].clone()
}

// ─── One bad slot ───────────────────────────────────────

#[test]
fn a_corrupt_slot_does_not_wipe_the_other_kids_saves() {
    let backend = InMemoryBackend::with_raw_saves(&format!("[{},null,{}]", ari(), corrupt_noa()));

    let slots = backend.load_all();
    assert_eq!(slots[0].as_ref().map(|s| s.name.as_str()), Some("Ari"), "Ari's save still loads");
    assert!(slots[1].is_none(), "slot 2 was free");
    assert!(slots[2].is_none(), "Noa's save can't be read by this build");

    let unreadable = backend.unreadable_slots();
    assert!(unreadable[0].is_none() && unreadable[1].is_none());
    let noa = unreadable[2].as_ref().expect("Noa's slot is reported unreadable, not empty");
    assert_eq!(noa.name.as_deref(), Some("Noa"), "we still know whose file it is");
    assert_eq!(noa.raw, corrupt_noa());
}

#[test]
fn a_corrupt_slot_survives_saves_to_other_slots_byte_for_byte() {
    let backend = InMemoryBackend::with_raw_saves(&format!("[{},null,{}]", ari(), corrupt_noa()));

    // Ari keeps playing; a new kid starts in the free slot; Ari's file is deleted.
    let mut ari_save = backend.load_all()[0].clone().unwrap();
    ari_save.dum_dums += 5;
    backend.save_to(0, &ari_save);
    backend.save_to(1, &ari_save);
    backend.delete(0);

    let after = raw_slots(&stored(&backend));
    assert_eq!(after.len(), 3);
    assert_eq!(after[2], corrupt_noa(), "Noa's unreadable save is written back untouched");
    assert_eq!(after[0], "null");
    assert_eq!(backend.load_all()[1].as_ref().unwrap().dum_dums, 22);
}

#[test]
fn a_corrupt_slot_is_backed_up_once_under_its_own_key() {
    let backend = InMemoryBackend::with_raw_saves(&format!("[{},null,{}]", ari(), corrupt_noa()));
    for _ in 0..3 {
        backend.load_all();
    }

    let key = backup_key("2", &corrupt_noa());
    assert!(key.starts_with(&format!("{STORAGE_KEY}.corrupt.2.")));
    assert_eq!(backend.raw(&key), Some(corrupt_noa()), "a parent can recover Noa from the backup");
    let backups: Vec<_> = backend.keys().into_iter().filter(|k| k.contains(".corrupt.")).collect();
    assert_eq!(backups, vec![key], "reloading doesn't pile up copies");
}

#[test]
fn overwriting_an_unreadable_slot_still_leaves_the_backup() {
    // The title screen shouldn't offer this, but the backend holds the line
    // on its own: the original is backed up before anything replaces it.
    let backend = InMemoryBackend::with_raw_saves(&format!("[{},null,{}]", ari(), corrupt_noa()));
    let ari_save = backend.load_all()[0].clone().unwrap();
    backend.save_to(2, &ari_save);

    assert!(backend.load_all()[2].is_some());
    assert_eq!(backend.raw(&backup_key("2", &corrupt_noa())), Some(corrupt_noa()));
}

#[test]
fn an_unreadable_save_file_is_backed_up_before_anything_overwrites_it() {
    let garbage = "{\"not\": \"a slot array\"";
    let backend = InMemoryBackend::with_raw_saves(garbage);

    assert!(backend.load_all().iter().all(|s| s.is_none()));
    let ari_save = decode_first_save(MAIN_SAVES);
    backend.save_to(0, &ari_save);

    assert_eq!(backend.raw(&backup_key("file", garbage)).as_deref(), Some(garbage),
        "the whole unreadable value is kept for a grown-up");
    assert_eq!(backend.load_all()[0].as_ref().unwrap().name, "Ari");
}

/// Through the real game: a kid mashing "2" on a napping slot stays on the
/// title screen, and the save underneath is still there afterwards.
#[test]
fn a_kid_on_the_title_screen_cannot_start_over_a_napping_save() {
    let backend = InMemoryBackend::with_raw_saves(&format!("[null,{},{}]", corrupt_noa(), ari()));
    let before = backend.raw(robot_buddy_game::save::STORAGE_KEY).unwrap();
    let mut h = common::Harness::with_backend(3, backend.clone());
    assert_eq!(h.game.state, robot_buddy_game::game::GameState::Title);
    for _ in 0..3 {
        h.press(macroquad::prelude::KeyCode::Key2);
    }
    assert_eq!(h.game.state, robot_buddy_game::game::GameState::Title,
        "the napping slot must not open the new-game form");
    assert_eq!(backend.raw(robot_buddy_game::save::STORAGE_KEY).unwrap(), before,
        "nothing was written over the unreadable save");
}

fn decode_first_save(json: &str) -> SaveData {
    match decode_saves(json).slots.into_iter().next().unwrap() {
        StoredSlot::Save(s) => s,
        _ => panic!("slot 1 should decode"),
    }
}

// ─── Title screen ───────────────────────────────────────

#[test]
fn the_title_screen_never_offers_an_unreadable_slot_as_new() {
    let backend = InMemoryBackend::with_raw_saves(&format!("[null,{},{}]", corrupt_noa(), ari()));
    let layout = title_screen::layout_title(
        &backend.load_all(), &backend.unreadable_slots(), common::SCREEN);

    assert_eq!(layout.slots[0].primary_action, TitleActionKind::NewGame);
    assert_eq!(layout.slots[1].primary_action, TitleActionKind::Resting);
    assert!(layout.slots[1].delete_btn.is_none(), "nothing to click that could bury it");
    assert_eq!(layout.slots[2].primary_action, TitleActionKind::LoadGame);

    let press_2 = FrameInput::empty().with_key_pressed(macroquad::prelude::KeyCode::Key2);
    assert!(title_screen::handle_title_input(&layout, &press_2).is_none(),
        "pressing 2 on a resting slot does nothing");
    let (bx, by, _, _) = layout.slots[1].primary_btn;
    let tap = FrameInput::empty().with_mouse_click(bx + 1.0, by + 1.0);
    assert!(title_screen::handle_title_input(&layout, &tap).is_none());
}

#[test]
fn a_new_kid_starting_a_game_leaves_the_unreadable_slot_alone() {
    let backend = InMemoryBackend::with_raw_saves(&format!("[null,{},{}]", corrupt_noa(), ari()));
    let mut h = Harness::with_backend(1, backend.clone());
    assert_eq!(h.game.state, GameState::Title);

    h.start_new_game("Tali");

    let after = raw_slots(&stored(&backend));
    assert_eq!(after[1], corrupt_noa(), "Noa's save is untouched by Tali's first save");
    let slots = backend.load_all();
    assert_eq!(slots[0].as_ref().unwrap().name, "Tali");
    assert_eq!(slots[2].as_ref().unwrap().name, "Ari", "Ari's save is still there");
}

// ─── Migration from what `main` writes ──────────────────

#[test]
fn a_save_written_by_main_loads_and_migrates() {
    let backend = InMemoryBackend::with_raw_saves(MAIN_SAVES);
    let slots = backend.load_all();
    assert!(backend.unreadable_slots().iter().all(|u| u.is_none()));

    let ari = slots[0].as_ref().expect("Ari loads");
    assert_eq!(ari.name, "Ari");
    assert_eq!(ari.dum_dums, 17);
    assert_eq!(ari.pearls, 4);
    assert_eq!(ari.profile.math_band, 4);
    assert!(ari.profile.intake_completed);
    assert_eq!(ari.companion.as_ref().map(|c| c.kind.as_str()), Some("dolphin"));
    let worn: Vec<&str> = ari.wardrobe.worn_by(wardrobe::PLAYER).iter().map(String::as_str).collect();
    assert_eq!(worn, vec!["bow_tie", "hat"], "shop_owned moved onto the kid");
    assert!(ari.shop_owned.is_empty(), "in memory the wardrobe is the only truth");
    assert!(ari.seen_intros.contains(&"reef".to_string()), "a veteran diver skips the reef speech");
    assert!(ari.upgrades.is_empty());

    assert!(slots[1].is_none());
    assert_eq!(slots[2].as_ref().unwrap().name, "Noa");
}

#[test]
fn a_save_written_by_main_round_trips() {
    let backend = InMemoryBackend::with_raw_saves(MAIN_SAVES);
    let ari = backend.load_all()[0].clone().unwrap();
    backend.save_to(0, &ari);

    let first: serde_json::Value = serde_json::from_str(&stored(&backend)).unwrap();
    let reloaded = backend.load_all();
    let again = reloaded[0].as_ref().unwrap();
    assert_eq!(again.wardrobe, ari.wardrobe);
    assert_eq!(again.seen_intros, ari.seen_intros);
    assert_eq!(again.dum_dums, 17);
    assert_eq!(again.profile.math_band, 4);

    // A second load → save changes nothing: migration is a fixed point.
    backend.save_to(0, again);
    backend.save_to(2, reloaded[2].as_ref().unwrap());
    let second: serde_json::Value = serde_json::from_str(&stored(&backend)).unwrap();
    assert_eq!(first, second);
}

// ─── Rollback: `main` reading what this build writes ────

/// `main`'s `SaveData` field set, copied from `git show main:robot-buddy-game/src/save.rs`.
/// If this build writes something `main` can't read, `main`'s
/// `unwrap_or([None, None, None])` would read "no saves" and wipe all three.
#[derive(Serialize, Deserialize)]
struct MainSaveData {
    version: u32,
    name: String,
    gender: robot_buddy_game::save::Gender,
    map_id: String,
    player_x: usize,
    player_y: usize,
    player_dir: robot_buddy_game::sprites::Dir,
    sparky_x: usize,
    sparky_y: usize,
    #[serde(default)]
    sparky_parked: bool,
    #[serde(default, skip_serializing)]
    #[allow(dead_code)]
    math_band: Option<u8>,
    dum_dums: u32,
    #[serde(default)]
    pearls: u32,
    play_time: f32,
    timestamp: u64,
    #[serde(default)]
    gifts_given: std::collections::HashMap<String, u32>,
    #[serde(default = "LearnerProfile::new")]
    profile: LearnerProfile,
    #[serde(default)]
    companion: Option<robot_buddy_game::save::CompanionSave>,
    #[serde(default)]
    shop_owned: Vec<String>,
    #[serde(default)]
    color_choice: String,
    #[serde(default)]
    satisfied_gates: Vec<String>,
    #[serde(default)]
    paid_tolls: Vec<String>,
    #[serde(default)]
    fuel: u32,
}

#[test]
fn main_can_still_read_what_this_build_writes_and_keeps_the_kids_cosmetics() {
    let backend = InMemoryBackend::with_raw_saves(MAIN_SAVES);
    let mut ari = backend.load_all()[0].clone().unwrap();
    // Ari hands the bow tie to Echo, then buys jet boots.
    ari.wardrobe.hand_over(wardrobe::PLAYER, "dolphin", "bow_tie");
    ari.wardrobe.put_on(wardrobe::PLAYER, "jet_boots");
    ari.upgrades.push("diving_net".into());
    backend.save_to(0, &ari);

    let on_main: [Option<MainSaveData>; 3] = serde_json::from_str(&stored(&backend))
        .expect("main must parse this build's saves, or it wipes every slot");
    let main_ari = on_main[0].as_ref().unwrap();
    assert_eq!(main_ari.name, "Ari");
    assert_eq!(main_ari.dum_dums, 17);
    assert_eq!(main_ari.shop_owned, vec!["hat".to_string(), "jet_boots".to_string()],
        "main sees what the kid is wearing (Echo's bow tie is Echo's)");
    assert!(on_main[2].is_some(), "Noa survives the rollback too");

    // And rolling forward again: main rewrites without a wardrobe; this build
    // puts the kid's cosmetics back on them.
    let main_wrote = serde_json::to_string(&on_main).unwrap();
    let forward = InMemoryBackend::with_raw_saves(&main_wrote);
    let back = forward.load_all()[0].clone().unwrap();
    let worn: Vec<&str> = back.wardrobe.worn_by(wardrobe::PLAYER).iter().map(String::as_str).collect();
    assert_eq!(worn, vec!["hat", "jet_boots"]);
}

#[test]
fn the_rollback_mirror_never_overrides_a_real_wardrobe() {
    // In this build's own saves the wardrobe is the truth; a stale mirror
    // must not put swag back on a kid who gave it away.
    let backend = InMemoryBackend::with_raw_saves(MAIN_SAVES);
    let mut ari = backend.load_all()[0].clone().unwrap();
    ari.wardrobe.hand_over(wardrobe::PLAYER, "dolphin", "hat");
    backend.save_to(0, &ari);

    let mut json: serde_json::Value = serde_json::from_str(&stored(&backend)).unwrap();
    json[0]["shop_owned"] = serde_json::json!(["hat", "bow_tie"]);
    let tampered = InMemoryBackend::with_raw_saves(&json.to_string());
    let back = tampered.load_all()[0].clone().unwrap();
    assert!(!back.wardrobe.is_wearing(wardrobe::PLAYER, "hat"), "Echo still has the hat");
    assert!(back.wardrobe.is_wearing("dolphin", "hat"));
}

/// Hiding the tab saves once, not on every frame the tab stays hidden.
#[test]
fn a_hidden_tab_saves_once_not_every_frame() {
    let backend = InMemoryBackend::default();
    let mut h = common::Harness::with_backend(3, backend.clone());
    h.start_dev_game();
    h.game.map = robot_buddy_game::tilemap::Map::home(); // the dev map never saves
    h.idle();
    let before = backend.writes();
    backend.set_page_hidden(true);
    h.advance(120);
    assert_eq!(backend.writes() - before, 1, "one save when the tab hid");
    backend.set_page_hidden(false);
    h.advance(10);
    backend.set_page_hidden(true);
    h.advance(10);
    assert_eq!(backend.writes() - before, 2, "and one more the next time it hides");
}
